name: Bots CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - "packages/nouns-bots/**"
    branches:
      - "**"

jobs:
  build_and_push:
    name: Build and Push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GCR
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.bots
          push: true
          tags: user/app:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
